### ISSUE TITLE
[ENHANCEMENT] Detect UUID

### ISSUE THREAD

**Issue by JoshuaMart** [minamo7sen/burp-JS-Miner#4]
Hello,
Thanks for JSMiner, very useful !

While browsing an application, I was able to detect some UUIDs that were useful but which JSMiner does not detect because the secrets regex does not seem to be adapted for a UUID.

So I think it might be interesting to add UUID detection in JSMiner? The following regex should do the job
```
[a-fA-F\d+]{8}-[a-fA-F\d+]{4}-4[a-fA-F\d+]{3}-[a-fA-F\d+]{4}-[a-fA-F\d+]{12}
```
On the other hand I don't know if it can really be counted as a secret, so I don't know if it belongs in `SECRETS_REGEX`.

Regards

**Comment by minamo7sen** [comment]
Hello,

Thanks for getting in touch.

I don't believe UUID should be treated as a secret. In general, I think that UUID should not be used - for example - as a security token, see [RFC-4122 - Security Considerations](https://www.rfc-editor.org/rfc/rfc4122.html#section-6):
> Do not assume that UUIDs are hard to guess; they should not be used as security capabilities.

Despite the fact that some implementations might incorporate cryptographic functions to enhance the strength of its randomness.

I think you might want to check out this Burp extension `UUID Detector`:
https://portswigger.net/bappstore/65f32f209a72480ea5f1a0dac4f38248

**Comment by JoshuaMart** [comment]
Sorry, my message is certainly not clear.
I also don't think that a UUID should be treated as a secret nor that it should be used as such.

To put more context in my proposal, I was hunting on an application when I discovered valid UUID (user belongings) in a JS file (which the suggested extension does not detect).

Although they are not secrets, UUIDs are often used as a defense mechanism against IDORs and this is unfortunately not enough, especially when we find a way to get one or more valid UUIDs as in this case.

Regards

**Comment by minamo7sen** [comment]
Hello again,

Thanks for the clarification.

I understand there might be a need for something to detect those UUIDs, I quickly checked the source code of the burp extension I mentioned above and I think it can do even a better job than me adding that UUID regex. It sort of analyze the extracted UUIDs with the version and try to provide some info. Not sure if this may help, I didn't try it myself.

But I would rather avoid adding a feature that is already implemented in another burp extension. I don't see any benefit of doing so, it may just produce more false positives from the extension, which is undesirable.

**Comment by JoshuaMart** [comment]
Okay,
I understand, thanks for the answer :)

Regards
