### ISSUE TITLE
Flag on Basic auth secrets

### ISSUE THREAD

**Issue by RandomRobbieBF** [minamo7sen/burp-JS-Miner#5]
Hey,

I have a js file with the following.

`Authorization:"Basic  c21lZ3NtZWdzbWVnYWRzMTIzMTMxMjMx"`

any way to get it to highlight stuff like this? as it would be really handy.

**Comment by minamo7sen** [comment]
Hi,

Yes, that's possible. I'll release an update soon.

**Comment by minamo7sen** [comment]
This has been added in v1.16.
